Repository Hexlet/runit, pull requests merged in 2022-10, with the labels that each got.

#11 Updating the layout of the main project page
  views/landing/fonts/Onest-bold.woff
  views/landing/fonts/Onest-light.woff
  views/landing/fonts/Onest-regular.woff
  views/landing/images/Tota-13.png
  views/landing/images/blank.png
  views/landing/images/checked.svg
  views/landing/images/code.png
  views/landing/images/logo.png
  views/landing/images/os.png
  views/landing/images/person.png
  views/landing/images/share.png
  views/landing/images/tag.png
  views/landing/landing-editor.pug
  views/landing/modules/footer.pug
  views/landing/modules/header.pug
  views/landing/styles/normalize.css
  views/landing/styles/style.css
Labels: hacktoberfest-accepted

#15 fix logout button
  app/javascript/components/Navbar.jsx
  app/javascript/providers/AuthProvider.jsx
Labels: bug, frontend, hacktoberfest-accepted

#16 code correction based on comments
  views/landing/fonts/Onest-bold.woff
  views/landing/fonts/Onest-light.woff
  views/landing/fonts/Onest-regular.woff
  views/landing/images/checked.svg
  views/landing/landing-editor.pug
  views/landing/modules/footer.pug
  views/landing/modules/header.pug
  views/landing/styles/normalize.css
  views/landing/styles/style.css
Labels: frontend, hacktoberfest-accepted
